version: '3.7'

services:
    rabbitmq:
        container_name: "rabbitmq-container"
        build:
            context: ./rabbitmq-queue
        environment:
            RABBITMQ_DEFAULT_USER: "rabbitmq"
            RABBITMQ_DEFAULT_PASS: "rabbitmq"
            RABBITMQ_DEFAULT_VHOST: "/"
        ports:
            - "15672:15672"
            - "5672:5672"
        restart: always
